# Generated by Django 5.2.15 on 2026-07-04 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TranslationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pdf", models.FileField(upload_to="input/%Y/%m/")),
                (
                    "original_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("source_lang", models.CharField(default="en", max_length=8)),
                ("target_lang", models.CharField(default="ru", max_length=8)),
                ("provider", models.CharField(blank=True, default="", max_length=64)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("options", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("stage", models.CharField(blank=True, default="", max_length=32)),
                ("progress", models.FloatField(default=0.0)),
                ("outputs", models.JSONField(blank=True, default=dict)),
                (
                    "assets_dir",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("report", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SegmentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("kind", models.CharField(max_length=16)),
                ("source_text", models.TextField()),
                ("translation", models.TextField(blank=True, default="")),
                ("corrected", models.TextField(blank=True, default="")),
                ("ok", models.BooleanField(default=True)),
                ("issues", models.JSONField(blank=True, default=list)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="api.translationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("job", "order")},
            },
        ),
    ]
