# Generated by Django 5.2.15 on 2026-07-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_serverconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationjob",
            name="pause_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="translationjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("partial", "Partial"),
                    ("failed", "Failed"),
                    ("paused", "Paused"),
                ],
                default="queued",
                max_length=16,
            ),
        ),
    ]
