# Generated by Django 5.2.15 on 2026-07-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_translationjob_pause_requested_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationjob",
            name="stage_plan",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
