# Generated by Django 5.2.15 on 2026-07-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_translationjob_stage_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationjob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
